"""empty message

Revision ID: 1ce793d5f272
Revises: 49261e9ebb12
Create Date: 2019-05-30 12:37:33.430654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce793d5f272'
down_revision = '49261e9ebb12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachment', 'type',
               existing_type=sa.VARCHAR(length=90),
               nullable=True)
    op.alter_column('attachment', 'url',
               existing_type=sa.VARCHAR(length=90),
               nullable=True)
    op.create_unique_constraint(None, 'attachment', ['id'])
    op.create_unique_constraint(None, 'chat', ['id'])
    op.alter_column('member', 'last_readed_message',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'member', ['id'])
    op.create_unique_constraint(None, 'message', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'message', type_='unique')
    op.drop_constraint(None, 'member', type_='unique')
    op.alter_column('member', 'last_readed_message',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'chat', type_='unique')
    op.drop_constraint(None, 'attachment', type_='unique')
    op.alter_column('attachment', 'url',
               existing_type=sa.VARCHAR(length=90),
               nullable=False)
    op.alter_column('attachment', 'type',
               existing_type=sa.VARCHAR(length=90),
               nullable=False)
    # ### end Alembic commands ###
