"""empty message

Revision ID: 2b2913105c46
Revises: 1e354c929dad
Create Date: 2019-05-29 02:45:12.698348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2913105c46'
down_revision = '1e354c929dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'person', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    # ### end Alembic commands ###
