"""empty message

Revision ID: ba19e9cf5ad7
Revises: 1ce793d5f272
Create Date: 2019-06-05 23:59:09.618664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba19e9cf5ad7'
down_revision = '1ce793d5f272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastName', sa.String(length=90), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastName')
    # ### end Alembic commands ###
